### PR TITLE
作成日で検索

### PR DESCRIPTION
**Pull request by tomoaki317**
作成日で検索

### CODE REVIEW

**Comment by tomoaki317** [comment]
https://developer.zendesk.com/api-reference/help_center/help-center-api/search/

**Comment by toru-takahashi** [comment]
@tomoaki317 Thank you for submitting this. 

- The cron behavior will be changed to daily from hourly. 

But, for me, there is no big issue. So, I'll merge it.

**Comment by toru-takahashi** [comment]
But, please make sure you wanted to merge this change to your code or not.

**Comment by toru-takahashi** [comment]
@tomoaki317 I noticed created_after is not supported by v2/help_center/incremental/articles endpoint. I'll revert this change.

**Pull request merged**
